version: "3.8"
services:
  wg-easy:
    image: ghcr.io/wg-easy/wg-easy
    container_name: wg-easy
    environment:
      # Replace with your actual public IP or hostname
      - WG_HOST=your_server_public_ip_or_hostname
      - WG_PORT=51820
      - WG_DEFAULT_ADDRESS=10.8.0.x # Optional: set a default IP range for clients, e.g., 10.8.0.0/24
      - PASSWORD=your_admin_password # **CRITICAL: Change this to a strong password**
      # Optional: set timezone
      - TZ=Asia/Yangon # Adjust for your timezone
    volumes:
      - ./wg-easy-data:/etc/wireguard
    ports:
      - 51820:51820/udp
      - 51821:51821/tcp # Web UI port, change if needed
    cap_add:
      - NET_ADMIN
      - SYS_MODULE # Required for WireGuard kernel module on some hosts
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_l3_response=1
    restart: unless-stopped
